import Link from 'next/link'
import Head from "next/head";
import { FC, ReactNode } from 'react'

type Props = {
  title: string
  children: ReactNode
}

export default function Layout({ children, title = "HP by Nextjs"}:Props) {
  return (
    <>
     <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className='bg-gray-800'>
        <h1>しゅんでぃーのブログ</h1>
      </header>
      <main className='bg-gray-700'>
        {children}
      </main>
      <footer>

      </footer>
    </>
  )
}